Repository no-waste-app/no-waste, pull requests merged in 2021-01, with the labels that each got.

#2 Add UI CI pipeline
  .github/workflows/node.js.yml
  .gitlab-ci.yml
Labels: build

#5 Remove old backend
  manage.py
  mysite/__init__.py
  mysite/asgi.py
  mysite/settings.py
  mysite/urls.py
  mysite/wsgi.py
  polls/__init__.py
  polls/admin.py
  polls/apps.py
  polls/migrations/0001_initial.py
  polls/migrations/__init__.py
  polls/models.py
  polls/tests.py
  polls/urls.py
  polls/views.py
  requirements.txt
Labels: backend

#3 Backend initial commit
  backend/.gitignore
  backend/README.md
  backend/no_waste.py
  backend/requirements.txt
Labels: backend

#8 Add k3s and skaffold configuration
  README.md
  skaffold.yaml
  ui/.dockerignore
  ui/Dockerfile
  ui/k8s/deployment.yaml
  ui/nginx.conf
  ui/tools/backend/.dockerignore
  ui/tools/backend/Dockerfile
  ui/tools/backend/k8s/deployment.yaml
Labels: DevOps

#4 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: build

#9 Update UI
  ui/.eslintrc.js
  ui/.gitignore
  ui/package.json
  ui/src/About.test.tsx
  ui/src/About.tsx
  ui/src/App.css
  ui/src/App.tsx
  ui/src/CompleteProducts.test.tsx
  ui/src/CompleteProducts.tsx
  ui/src/MainPage.tsx
  ui/src/ProductList.test.tsx
  ui/src/ProductsList.tsx
  ui/src/Recipes.test.tsx
  ui/src/Recipes.tsx
  ui/src/mocks/browser.ts
  ui/src/mocks/handlers.ts
  ui/src/mocks/server.ts
  ui/src/models.ts
  ui/src/service.ts
  ui/src/setupTests.ts
  ui/tools/backend/.gitignore
  ui/tools/backend/data/products.json
  ui/tools/backend/data/recipes.json
  ui/tools/backend/package.json
  ui/tools/backend/src/index.ts
  ui/tools/backend/yarn.lock
  ui/yarn.lock
Labels: UI

#11 Recipes can be filtered now
  ui/src/MainPage.tsx
  ui/src/Recipes.test.tsx
  ui/src/Recipes.tsx
  ui/src/mocks/handlers.ts
  ui/tools/backend/src/index.ts
Labels: UI
